#!/usr/bin/python3

# Remote, SSH/SFTP profile manager
#
# author: Sydney Ann Mason
# version: 2.0
# date: 2019-05-09

# Imports
import sys # Allows you to access system information
import subprocess # Allows you to run CLI commands as a subprocess
from pathlib import Path # Allows you to grab the user Home Directory

# Checks for profile name
# If it does, run SSH or SFTP on the paired url
# If it doesn't, inform user and exits
def exec_proc(cmd, pname):
    # True if command has been ran
    ran = False
    # Gets path to profile list
    path = str(Path.home()) + '/.config/remote/remote_profiles'
    # Reads in profiles from file
    with open(path, 'r') as pfile:
        profiles = [line.strip() for line in pfile]
    # Finds profile and runs url as subprocess
    for profile in profiles:
        line = profile.split()
        if line[0] == pname:
            subprocess.run([cmd + ' ' + line[1]], shell=True)
            ran = True
            break
    # Prints message to screen if command was never run
    if ran == False:
        print(pname + ' was not found in list of profiles')

# Checks is a profile name or url exists
# If it does, informs user and exits
# If it doesn't, appends it to list of profiles
def add_profile(args):
    if len(args) > 2:
        add_profile(args[2:])
    pname = args[0]
    purl = args[1]
    # True if  name or url already exists in file (default: false)
    exists = False
    # Gets path to profile list
    path = str(Path.home()) + '/.config/remote/remote_profiles'
    # Reads in profiles from file
    with open(path, 'r') as pfile:
        profiles = [line.strip() for line in pfile]
    # Checks to make sure that profile name and url are not in use
    for profile in profiles:
        line = profile.split()
        if pname == line[0]:
            print(pname + ' already exists.' + '\n' + 'Run "remote list" for more info.')
            exists = True
            break
        elif purl == line[1]:
            print(purl + ' already exists.' + '\n' + 'Run "remote list" for more info.')
            exists = True
            break
    # Writes profile to list
    if exists == False:
        with open(path, 'a') as pfile:
            pfile.write(pname + ' ' + purl + '\n')

# Edit profile information
def edit_profile(args):
    if len(args) > 2:
        edit_profile(args[2:])
    pold = args[0]
    pnew = args[1]
    path = str(Path.home()) + '/.config/remote/remote_profiles'
    with open(path, 'r') as pfile:
        profiles = [line.strip() for line in pfile]
    for profile in profiles:
        if pold in profile:
            profiles[profiles.index(profile)] = profile.replace(pold, pnew, 1);
            break
    with open(path, 'w') as pfile:
        for profile in profiles:
            pfile.write(profile + '\n')

# Looks for and deletes specified profile
def remove_profile(args):
    for word in args:
        # Gets path to profile list
        path = str(Path.home()) + '/.config/remote/remote_profiles'
        # Reads in profiles from list
        with open(path, 'r') as pfile:
            profiles = [line.strip() for line in pfile]
        # Rewrites profilse minus one deleted one
        with open(path, 'w') as pfile:
            for profile in profiles:
                line = profile.split()
                if word != line[0]:
                    pfile.write(profile + '\n')

# Displays profiles to screen
def list_profile():
    # Gets path to profile list
    path = str(Path.home()) + '/.config/remote/remote_profiles'
    # Reads in profiles from file
    with open(path, 'r') as pfile:
        profiles = [line.strip() for line in pfile]
    # Prints profiles to screen
    for profile in profiles:
        print(profile)

# Displays help menu to screen
def help():
    print('remote is an ssh/sftp profile manager designed to be terminal emulator agnostic. It allows you to\n' +
            'easily add, view, delete, and run ssh or sftp with a list of known profiles.\n')
    print('remote stores known profiles in ${HOME}/.config/remote\n')
    print('Commands:')
    print('ssh - looks for and executes ssh on selected profile.\n\tUsage: remote ssh foo')
    print('sftp - similar to ssh, except it runs sftp on selected profile.\n\tUsage: remote sftp sftp foo')
    print('save - checks to see if profile name or url from a given list already exists in a pairing, appends them to the known pairings list if they don\'t.\n\t' + 'Usage: remote save foo bar')
    print('edit - looks for and replaces profile or url in pairing.\n\tUsage: remote edit foo bar')
    print('remove - looks and deletes selected profile(s) from list of known profiles.\n\tUsage: remote remove foo')
    print('print - displays all known profiles to the screen.\n\tUsage: remote print')
    print('help - displays this info to the screen\n\tUsage: do what you just did')

# Parses user input and determines the next best course of action
def main(args):
    # In each nested conditonal successeful param checks are first,
    # then all param num failures are list
    try:
        # For SSH/SFTP
        if args[0] == 'ssh' or args[0] == 'sftp':
            if len(args) == 2:
                exec_proc(args[0], args[1])
            elif len(args) > 2:
                print(args[0] + ' can only take 1 argument.'+ '\n' + 'Run "remote help" for more info')
            elif len(args) < 2:
                print(args[0] + ' needs 1 argument.' + '\n' + 'Run "remote help" for more info')
        # For saving new profiles
        elif args[0] == 'save':
            if len(args[1:])%2 != 0:
                print(args[0] + ' needs an equal number of profiles to urls.' + '\n' + 'Run "remote help" for more info')
            elif len(args) >= 3:
                add_profile(args[1:])
            elif len(args) < 3:
                print(args[0] + ' needs at least 3 arguments.' + '\n' + 'Run "remote help" for more info')
        elif args[0] == 'edit':
            if len(args[1:])%2 != 0:
                print(args[0] + ' needs and equal number of before and after items.' + '\n' + 'Run "remote help" for more info')
            elif len(args) >= 3:
                edit_profile(args[1:])
            elif len(args) < 3 :
                print(args[0] + ' needs at least 3 arguments.' + '\n' + 'Run "remote help" for more info')
        # For deleting known profiles
        elif args[0] == 'remove':
            if len(args) >= 2:
                remove_profile(args[1:])
            elif len(args) < 2:
                print(args[0] + ' needs at least 1 argument.' + '\n' + 'Run "remote help" for more info')
        # For seeing profiles
        elif args[0] == 'print':
            if len(args) == 1:
                list_profile()
            elif len(args) > 1:
                print(args[0] + ' takes no arguments.' + '\n' + 'Run "remote help" for more info')
        # For gettting help
        elif args[0] == 'help':
            if len(args) == 1:
                help()
            elif len(args) > 1:
                print(args[0] + ' takes no arguments.' + '\n' + 'Run "remote help" for more info')
        else:
            print(args[0] + ' command not found')
    except:
        print('Unexpected error: ' + sys.exc_info()[0])

# Calls main
if __name__ == "__main__":
    main(sys.argv[1:]) #drops remote from list of command line arguments
